# Generated by Django 2.1.2 on 2018-10-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default='', verbose_name='价格'),
        ),
    ]
