# Generated by Django 2.1.2 on 2018-10-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181030_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
    ]
