# Generated by Django 2.1.2 on 2018-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.CharField(default='', max_length=16, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(max_length=32, verbose_name='类别名'),
        ),
    ]
